### PR TITLE
Julian Smith De Niro Assignment 1

### PR DESCRIPTION
**Pull request by juliansd**

### CODE REVIEW

**Comment by dagoch** [comment]
Hi Julian,

You need to create a new pull request, for the assignment_01 branch, instead of master.  Please resubmit.

David

**Comment by juliansd** [comment]
Ok I’m in class right now it ends at 7:50 so I’ll be home around 8pm I’ll
do it then.

**Comment by juliansd** [comment]
Hi Professor,
I just made another pull request, is it the correct branch?

**Comment by dagoch** [comment]
Not quite right.  The left side of the arrow is the destination repo and
branch.  You should select the assignment_01 branch there.

**Comment by juliansd** [comment]
Is this correct?

**Comment by dagoch** [comment]
I didn't get a new pull request yet.

**Comment by juliansd** [comment]
Yeah I sent a screen shot to make sure it was correct did you not get it?

**Comment by juliansd** [comment]
Hi professor,
Did my pull request for assignment 1 work?

**Comment by dagoch** [comment]
Hi Julian,

It looks like this pull request is just asking me to merge my master branch
into my assignment_01 branch.  You need to do the pull request from your
fork to my master repo.

But first you need to do some reorganization in your repo.  It looks like
you rennamed the _A01_Master folder to your own folder, which will cause a
conflict because git will think you've deleted that folder.  So you need to
leave the Master folder in place and just duplicate it (you may need to
re-pull from the master repo to get this, or revert some of your commits.)
Also, the name of the folder you create shouldn't start with an underscore,
it should just be: A01_jsd410

And then it looks like you've copied an entire Unity project structure into
your Hello Unity! folder inside your assignment folder.  Please, instead
use the other folders inside your A01_jsd410 folder: put the scene for your
assignment inside the Scenes folder, and your scripts in the Scripts
folder, etc.  We set up the folder structure to make things cleaner and
simpler.

Then when you've done that, submit a pull request that looks like this:


Let me know if you have any other questions.  Also, Siyuan has office hours
today, or you can come to my office hour before class tomorrow, if you need
more help.

Thanks.

David​

**Pull request closed without merging**
